# Generated by Django 5.0 on 2025-02-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curl_pattern', models.CharField(choices=[('2A', '2A'), ('2B', '2B'), ('2C', '2C'), ('3A', '3A'), ('3B', '3B'), ('3C', '3C'), ('4A', '4A'), ('4B', '4B'), ('4C', '4C')], max_length=3)),
                ('hair_type', models.CharField(choices=[('Thin', 'Thin'), ('Medium', 'Medium'), ('Thick', 'Thick')], max_length=6)),
                ('vegan_preference', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TriedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Awful, never again'), (2, 'Not great'), (3, 'Okay, would try again'), (4, 'Good, recommend'), (5, 'Amazing, holy grail product')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.hairproduct')),
            ],
        ),
    ]
