# Generated by Django 5.0 on 2025-03-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_hairquiz_triedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairproduct',
            name='helpful_areas',
        ),
        migrations.AddField(
            model_name='hairproduct',
            name='growth_areas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hairproduct',
            name='hold_level',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('strong', 'Strong')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hairproduct',
            name='sulfate_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='dyed_or_bleached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='growth_areas',
            field=models.CharField(choices=[('Hydrating', 'Hydrating'), ('Conditioning', 'Conditioning'), ('Moisturizing', 'Moisturizing'), ('Clarifying', 'Clarifying'), ('Damage Control', 'Damage Control'), ('Strengthening', 'Strengthening'), ('Repair', 'Repair'), ('Definition', 'Definition')], default='Hydrating', max_length=20),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='hair_length',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='hold_preference',
            field=models.CharField(choices=[('Soft', 'Soft'), ('Medium', 'Medium'), ('Strong', 'Strong')], default='Medium', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='maintenance_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='oiliness_timing',
            field=models.CharField(choices=[('1 day', '1 day'), ('2 days', '2 days'), ('3+ days', '3+ days')], default='Days', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='price_range',
            field=models.CharField(choices=[('$', 'Budget'), ('$$', 'Mid-Range'), ('$$$', 'High-End')], default='Expensive', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='prone_to_flakes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='scalp_condition',
            field=models.CharField(choices=[('Oily', 'Oily'), ('Flaky', 'Flaky'), ('Balanced', 'Balanced')], default='Dry', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='sensitive_scalp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='styling_product',
            field=models.CharField(choices=[('Mousse', 'Mousse'), ('Gel', 'Gel')], default='Gel', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='wash_frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Every 2-3 days', 'Every 2-3 days'), ('Weekly', 'Weekly')], default='Everyday', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairquiz',
            name='workout_frequency',
            field=models.CharField(choices=[('Rarely', 'Rarely'), ('1-2 times/week', '1-2 times/week'), ('3+ times/week', '3+ times/week')], default='Everyday', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hairproduct',
            name='weight',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], max_length=1),
        ),
    ]
